name: Publish Extension

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Extension to Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Extension
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "*.zip"

      - name: Get Release File Name
        run: echo "EDGE_RELEASE_FILE=$(ls | grep *.zip)" >> $GITHUB_ENV
      - name: Test
        run: echo ${{env.EDGE_RELEASE_FILE}}

      - name: Publish to store
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.BPP_KEYS }}
          chrome-file: "${{env.EDGE_RELEASE_FILE}}"
          edge-file: "${{env.EDGE_RELEASE_FILE}}"
